<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\..\common.props" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <AssemblyName>ca</AssemblyName>
    <GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
    <GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GenerateAssemblyCopyrightAttribute>false</GenerateAssemblyCopyrightAttribute>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
    <RootNamespace>Kontecg</RootNamespace>
    <Description>ca - generate certificates for Kontecg Platform</Description>
    <ApplicationIcon>..\..\portafolio\bot.ico</ApplicationIcon>
    <OutputPath>bin\</OutputPath>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <FileVersion>0.1.0.0</FileVersion>
    <InformationalVersion>0.1.0-alpha.206+Branch.develop.Sha.786cb4abad273ad22dc2aad35a512eb4173c262b</InformationalVersion>
    <Version>0.1.0-alpha.206</Version>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.7" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Kontecg.Core\Kontecg.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="cm.xlsx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>